name: Generate Profile Stats

on:
  schedule:
    - cron: '0 0,12 * * *' # Runs twice a day at 12:00 AM and 12:00 PM UTC (5:30 AM/PM IST)
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate SVGs
        env:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
        run: |
          python generate_profile_stats.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Prashantsk45"
          git config --global user.email "Prashantsk.272@gmail.com"
          git add generated/*.svg
          # Only commit and push if there are changes
          git diff-index --quiet HEAD || (git commit -m "Auto-update profile statistics" && git push)
